![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Problem Statement: 
#### Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

*The returned dictionary should follow this format:*
```Python
{
  'mean': [axis1, axis2, flattened],
  'variance': [axis1, axis2, flattened],
  'standard deviation': [axis1, axis2, flattened],
  'max': [axis1, axis2, flattened],
  'min': [axis1, axis2, flattened],
  'sum': [axis1, axis2, flattened]
}
```
If a list containing less than 9 elements is passed into the function, it should raise a `ValueError` exception with the message: *"List must contain nine numbers."* The values in the returned dictionary should be lists and not Numpy arrays.

*For example, calculate([0,1,2,3,4,5,6,7,8]) should return:*

```Python
{
  'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
  'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
  'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178],
                         [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
  'max': [[6, 7, 8], [2, 5, 8], 8],
  'min': [[0, 1, 2], [0, 3, 6], 0],
  'sum': [[9, 12, 15], [3, 12, 21], 36]
}
```
![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Solution:
as per the first principles thinking..

In [1]:
import numpy as np

In [2]:
list_input = [0,1,2,3,4,5,6,7,8]
array = np.array(list_input).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
print('Calculating Mean...\n','\nAcross Rows:',array.mean(axis = 0).tolist(),'\n\
Across Columns:',array.mean(axis=1).tolist(),'\nFlattened:',array.mean())

Calculating Mean...
 
Across Rows: [3.0, 4.0, 5.0] 
Across Columns: [1.0, 4.0, 7.0] 
Flattened: 4.0


In [4]:
print('Calculating Variance...\n','\nAcross Rows:',array.var(axis = 0).tolist(),'\n\
Across Columns:',array.var(axis=1).tolist(),'\nFlattened:',array.var())

Calculating Variance...
 
Across Rows: [6.0, 6.0, 6.0] 
Across Columns: [0.6666666666666666, 0.6666666666666666, 0.6666666666666666] 
Flattened: 6.666666666666667


In [5]:
array.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [6]:
array.max(axis = 0)

array([6, 7, 8])

In [7]:
array.sum(axis =1)

array([ 3, 12, 21])

## Main Program:

In [8]:
def calculate(list):
    if len(list) != 9:
        raise ValueError('list must contain nine numbers.')
        
    arr = np.array(list).reshape(3,3)
    
    calculations = {
        'mean:':[arr.mean(axis =0).tolist(), arr.mean(axis = 1).tolist(),arr.mean()],
        'variance':[arr.var(axis=0).tolist(),arr.var(axis=1).tolist(),arr.var()],
        'standard deviation':[arr.std(axis=0).tolist(),arr.std(axis=1).tolist(),arr.std()],
        'max':[arr.max(axis=0).tolist(),arr.max(axis=1).tolist(),arr.max()],
        'min':[arr.min(axis=0).tolist(),arr.min(axis=1).tolist(),arr.min()],
        'sum':[arr.sum(axis=0).tolist(),arr.sum(axis=1).tolist(),arr.sum()],
    }
    return calculations

## Input Data:

In [9]:
input1_vals = [0,1,2,3,4,5,6,7,8]
output1 = calculate(input1_vals)

In [10]:
input2_vals = [9,1,5,3,3,3,2,9,0]
output2 = calculate(input2_vals)

## Testing:

In [11]:
result = {
    'test1':{'mean:': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
             'variance': [[6.0, 6.0, 6.0],[0.6666666666666666, 0.6666666666666666, 0.6666666666666666],6.666666666666667],
             'standard deviation': [[2.449489742783178,2.449489742783178,2.449489742783178],
                                    [0.816496580927726, 0.816496580927726, 0.816496580927726],2.581988897471611],
             'max': [[6, 7, 8], [2, 5, 8], 8],
             'min': [[0, 1, 2], [0, 3, 6], 0],
             'sum': [[9, 12, 15], [3, 12, 21], 36]},
    'test2':{'mean:': [[4.666666666666667, 4.333333333333333, 2.6666666666666665],[5.0, 3.0, 3.6666666666666665],
                       3.888888888888889],
             'variance': [[9.555555555555555, 11.555555555555557, 4.222222222222222],
                          [10.666666666666666, 0.0, 14.888888888888891],9.209876543209875],
             'standard deviation': [[3.0912061651652345,3.39934634239519,2.0548046676563256],
                                    [3.265986323710904, 0.0, 3.8586123009300755],3.0347778408328137],
             'max': [[9, 9, 5], [9, 3, 9], 9],
             'min': [[2, 1, 0], [1, 3, 0], 0],
             'sum': [[14, 13, 8], [15, 9, 11], 35]}
    
}

In [12]:
result['test1'] == output1

True

In [13]:
result['test2'] == output2

True

## Show the Outputs:

In [14]:
output1

{'mean:': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

In [15]:
output2

{'mean:': [[4.666666666666667, 4.333333333333333, 2.6666666666666665],
  [5.0, 3.0, 3.6666666666666665],
  3.888888888888889],
 'variance': [[9.555555555555555, 11.555555555555557, 4.222222222222222],
  [10.666666666666666, 0.0, 14.888888888888891],
  9.209876543209875],
 'standard deviation': [[3.0912061651652345,
   3.39934634239519,
   2.0548046676563256],
  [3.265986323710904, 0.0, 3.8586123009300755],
  3.0347778408328137],
 'max': [[9, 9, 5], [9, 3, 9], 9],
 'min': [[2, 1, 0], [1, 3, 0], 0],
 'sum': [[14, 13, 8], [15, 9, 11], 35]}

In [16]:
input3_vals = [3,4,2,5,1]
output3 = calculate(input3_vals)

ValueError: list must contain nine numbers.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

<img src="https://imgur.com/3g7LyTV.png" align = 'right' width="240">

$End$ $of$ $the$ $notebook...$